# Generated by Django 5.1.5 on 2025-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mqtt_client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensordata',
            name='gas_level',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
